// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMPPP.Infrastructure.Data;

#nullable disable

namespace TMPPP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426111821_sec")]
    partial class sec
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMPPP.Domain.Entities.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AthleteType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubscriptionBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Athletes");

                    b.HasDiscriminator<string>("AthleteType").HasValue("Athlete");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TMPPP.Domain.Entities.Coach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoachType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coach");

                    b.HasDiscriminator<string>("CoachType").HasValue("Coach");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TMPPP.Domain.Entities.AmateurAthlete", b =>
                {
                    b.HasBaseType("TMPPP.Domain.Entities.Athlete");

                    b.HasDiscriminator().HasValue("Amateur");
                });

            modelBuilder.Entity("TMPPP.Domain.Entities.ProfessionalAthlete", b =>
                {
                    b.HasBaseType("TMPPP.Domain.Entities.Athlete");

                    b.Property<int>("Ranking")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Pro");
                });

            modelBuilder.Entity("TMPPP.Domain.Entities.AmateurCoach", b =>
                {
                    b.HasBaseType("TMPPP.Domain.Entities.Coach");

                    b.HasDiscriminator().HasValue("AmateurCoach");
                });

            modelBuilder.Entity("TMPPP.Domain.Entities.ProfessionalCoach", b =>
                {
                    b.HasBaseType("TMPPP.Domain.Entities.Coach");

                    b.HasDiscriminator().HasValue("ProCoach");
                });
#pragma warning restore 612, 618
        }
    }
}
